### ISSUE TITLE
Version 4

### ISSUE THREAD

**Issue by abeimler** [abeimler/pro4trello#1]
The older Pro4Trello 3.x is a bit outdated, 
I've recently tried to update the older Code for fun and private usage:

https://github.com/abeimler/pro4trello/tree/v4

---

### Project and Codebase

- React and Vanilla JS
  - get rid of jQuery
  - less "stringify" HTML and CSS in code 
  - split big JavaScript Code into smaller Components
- use TypeScript
- update to Manifest V3
- update/parse data and cards on demand (avoid setTimeout)
- use [Atlassian Design System](https://atlassian.design/get-started)
- Add formatting, linter, ...

### Features

- [x] Recognize categories/projects
- [x] Recognize hashtags
- [x] Recognize custom tags - similar to Trello native Label - keep ???
- [x] Recognize time entries
- [x] Recognize price entries
- [x] Recognize priority (medium, high, critical)
- [x] Recognize points
- [x] Render simple markup
- [x] Display card numbers
- [x] ~~Display full-sized labels~~ (deprecated) - use Trellos native compact labels (?)
- [ ] ~~Beautify Card Description~~ - not much different than the native Trello ones with dark/light theme
- [x] ~~Full screen card details~~ - not much of a use (for me...)
- [ ] ~~Apply custom background~~ - use Trello Custom Backgrounds
- [x] Show list stats
- [x] Use the progress bar in the list stats
- [x] ~~Compact Board~~ - not much difference
- [x] Hide "Add a list.." input
- [ ] ~~Apply custom CSS~~ (deprecated) - Don't really use it, Trello update can break CSS settings ...
- [x] Board Settings - Per-board configuration
    - [x] Exporting board configuration 
- [x] Global Settings - Global configuration for all boards
- [x] Auto-Hide Footer
- [x] Sync (Global) Boards (needs more Testing?)
- [x] ~~List Enchancements~~ - see new features
- [ ] horizontal lanes - TODO(optional): Show Cards in "Stack" (+ Compact Cards)

#### NEW Features

- [x] respect dark/light-theme
- [x] board/global list width (settings)
- [x] Update Filters (with multiple selections) - https://github.com/mdjekic/pro4trello/issues/29
   - [x] Priorities, Categories, Tags, and Hashtags can now be selected with a checkbox
   - [x] Filter "No Hashtags", "No Prios." etc. - https://github.com/mdjekic/pro4trello/issues/28 https://github.com/mdjekic/pro4trello/issues/34
   - [x] NEW Trello Labels Filter
   - [x] "Clean Filters"-Button
- [x] "Total Cards" display
- [x] Make some Popups and single Pages into modals (About, Share, etc.)
- [x] List Enhancements - in List Title (parsing) (experimental)
   - [x] Can be used across the shared Boards (similar to Cards Titles) 
      - not saved anymore in the local settings
   - Example `Ideas ==#202214== <250px>`  -> "Ideas" (parse example not final ???)
      - [x] Custom background-color: `==#202214==` use `#202214` Color for Background (in List)
      - [-] Custom list width: `<250px>` make List `250px` width

##### TODO

- [-] Update Card/List on changes
   - Only updates on Page reload ... 
- [ ] injecting CSS with Manifest V3 - https://developer.chrome.com/docs/extensions/reference/scripting/#method-insertCSS
- [ ] Extension Popup (similar to "Trello4Pro"-Menu)
- [-] Preserve Google Analytics
- [ ] More Testing/Bugfixes ???
- [-] Not sure if old Settings (from 3.x) still works...
   - keep old key names for settings
- [ ] Github Actions (packaging browser extension into .zip)

**Comment by jordan2175** [comment]
This looks fantastic. Are you still working on this?
